# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 96cb919def60854f7f1ad9a8509e6d74527c6fafb88710ab5e7cfd36587098f07cb837ed91bf8e463e09b138c3b4af4f93576994c52e39a3fe05b3afa4736fd5

test:
  secret_key_base: 06848116e3baa15c7a6677d6855e776e65df5178700056edd9ddbfd16f3d7f26aa44e4086204b604a38d4b289c3c7ce2ae51be3d14476b1b0071aab65ac77356

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
